### PR TITLE
Fix for odd f/w

### PR DESCRIPTION
**Pull request by britkat1980**
Update to allow access to alternative battery charge and discharge energy totals on some versions of f/w

### CODE REVIEW

**Comment by dewet22** [comment]
Thanks for this. What's the difference between these registers (IR 105 & 106) and the other battery_total_(dis)charge registers (IR 180 & 181)? My gut feeling is the former is the total for the battery pack and should be equal to the latter for single battery systems. In multi-battery systems, do the latter indicate the cumulative totals across all battery packs?

**Comment by britkat1980** [comment]
For some users registers 180&181 don't return data (0 values), so they need to get battery energy details from 105&106. Not sure why, its due to variances in the firmware. GE haven't been able to really confirm what versions have which registers... So I use some logic in GivTCP to fetch from second register set if the "usual" ones don't return values

**Comment by dewet22** [comment]
Thanks! Do you remember off-hand which models return which values?

**Comment by britkat1980** [comment]
This is the problem... its not specific to any one model, in theory applies to f/w prior to 449 (but even that's not consistent afaik)

**Comment by dewet22** [comment]
Understood. Thanks for the contribution!

**Pull request merged**
